### ISSUE TITLE
Error 400 (Invalid request) when installing from ST2 Package Control

### ISSUE THREAD

**Issue by Franky47** [filcab/SublimeLLDB#5]
When I try to install SublimeLLDB through Package Control on Sublime Text 2, I get the following error in the console:

Package Control: Error downloading package. HTTP error 400 downloading https://codeload.github.com/filcab/SublimeLLDB/zipball/master.
error: Package Control

Specs:
Mac OS X Mavericks 10.9.1
Sublime Text 2.0.2, build 2221
Sublime Package Control cache entry: "https://raw.github.com/filcab/SublimeLLDB/master/packages.json"

**Comment by filcab** [comment]
I'm sorry for not replying earlier.
I have no plans on updating this to work for SublimeText 3. I'm not using that text editor any more.

I'm going to tag this as abandoned, but feel free to ask about anything should anyone attempt to port it and need help.
I am also unsure of the functional status of this package since I haven't used it in a while.
