### ISSUE TITLE
Failed to install from package manager

### ISSUE THREAD

**Issue by nicola** [filcab/SublimeLLDB#6]
```
Package Control: Error downloading package. HTTP error 400 downloading https://codeload.github.com/filcab/SublimeLLDB/zipball/master.
```

**Comment by filcab** [comment]
I'm sorry for not replying earlier.
I have no plans on updating this to work for SublimeText 3. I'm not using that text editor any more.

I'm going to tag this as abandoned, but feel free to ask about anything should anyone attempt to port it and need help.
I am also unsure of the functional status of this package since I haven't used it in a while.
